# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_record.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import mysql.connector
import os
from tkinter import messagebox
import datetime
from datetime import datetime
import resources

class Ui_MainWindow(object): 
    def connect2db(self):
        self.con = mysql.connector.connect(
        host="localhost",
        user="root",
        password="Shailesh@123",
        database="loan_management",
        auth_plugin="caching_sha2_password" 
        )

    def resource_path(relative_path):
        """ Get absolute path to resource, works for dev and for PyInstaller """
        try:
                # PyInstaller creates a temp folder and stores path in _MEIPASS
                base_path = sys._MEIPASS
        except Exception:
                base_path = os.path.abspath(".")

        return os.path.join(base_path, relative_path)
    def clear(self):
        self.name.clear()
        self.fathername.clear()
        self.jewellery.clear()
        self.amount.clear()
        self.location.clear()
        self.weight.clear()

    def add_record(self):
        try: 
                if self.amount.text() == "":
                     messagebox.showerror("Error","Amount Is required")
                else:
                        amount  = self.amount.text()
                        amount = int(amount)
                if self.name.text() == "":
                     messagebox.showerror("Error","Name Is required")
                else:
                        name  = self.name.text()
                if self.fathername.text() == "":
                     messagebox.showerror("Error","Father's Name Is required")
                else:
                        fname = self.fathername.text()
                if self.location.text() == "":
                      messagebox.showerror("Error","Location Is required")
                else:
                        location = self.location.text()
                if self.jewellery.text() == "":
                      messagebox.showerror("Error","Type Of Jewellery Is required")
                else:
                        type = self.jewellery.text()
                if self.weight.text() == "":
                      messagebox.showerror("Error","Weight Is required")
                else:
                        weight = self.weight.text()
                        weight = float(weight)
                date = self.date.text()
                self.connect2db()
                cursor = self.con.cursor()
                # Prepare the SQL query
                query = "INSERT INTO all_records (amount,name,Father_name,Location,Date,Type,Weight) values (%s, %s, %s,%s,%s,%s,%s)"
                values = (amount,name,fname,location,date,type,weight)
                # Execute the query
                cursor.execute(query, values)
                self.con.commit()
                messagebox.showinfo("Success!","Data Inserted Successfully.")
                # Close the cursor and connection
                cursor.close()
                self.con.close()
                self.clear()

        except Exception as ex:
             messagebox.showerror("Error",f"Error Due to: {str(ex)}")            
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1300, 896)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/resources/resources/icons/add_record.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.toolBar = QtWidgets.QFrame(self.centralwidget)
        self.toolBar.setMinimumSize(QtCore.QSize(0, 30))
        self.toolBar.setMaximumSize(QtCore.QSize(16777215, 30))
        self.toolBar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.toolBar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.toolBar.setObjectName("toolBar")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.toolBar)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.toggleFrame = QtWidgets.QFrame(self.toolBar)
        self.toggleFrame.setMinimumSize(QtCore.QSize(30, 30))
        self.toggleFrame.setMaximumSize(QtCore.QSize(30, 30))
        self.toggleFrame.setStyleSheet("background-color: rgb(59, 65, 71);")
        self.toggleFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.toggleFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.toggleFrame.setObjectName("toggleFrame")
        self.toggleButton = QtWidgets.QPushButton(self.toggleFrame)
        self.toggleButton.setGeometry(QtCore.QRect(0, 0, 30, 30))
        self.toggleButton.setMinimumSize(QtCore.QSize(30, 30))
        self.toggleButton.setMaximumSize(QtCore.QSize(30, 30))
        self.toggleButton.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: rgb(0, 0, 0);\n"
"    border-left: 3px solid rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border-left: 3px solid rgb(255, 85, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(25, 25, 25);\n"
"}")
        self.toggleButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/icons8_menu.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toggleButton.setIcon(icon)
        self.toggleButton.setIconSize(QtCore.QSize(30, 30))
        self.toggleButton.setObjectName("toggleButton")
        self.horizontalLayout_2.addWidget(self.toggleFrame)
        self.headerFrame = QtWidgets.QFrame(self.toolBar)
        self.headerFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.headerFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.headerFrame.setObjectName("headerFrame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.headerFrame)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(218, 13, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.headerFrame)
        self.label.setStyleSheet("color: rgb(176, 176, 176);")
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(58, 13, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.userFrame = QtWidgets.QFrame(self.headerFrame)
        self.userFrame.setMinimumSize(QtCore.QSize(200, 30))
        self.userFrame.setMaximumSize(QtCore.QSize(200, 30))
        self.userFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.userFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.userFrame.setObjectName("userFrame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.userFrame)
        self.horizontalLayout_4.setContentsMargins(0, 0, 20, 0)
        self.horizontalLayout_4.setSpacing(5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_3.addWidget(self.userFrame)
        self.horizontalLayout_2.addWidget(self.headerFrame)
        self.verticalLayout.addWidget(self.toolBar)
        self.Body = QtWidgets.QFrame(self.centralwidget)
        self.Body.setStyleSheet("")
        self.Body.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Body.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Body.setObjectName("Body")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.Body)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Container = QtWidgets.QFrame(self.Body)
        self.Container.setStyleSheet("background-color: rgb(34, 34, 34);")
        self.Container.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Container.setObjectName("Container")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.Container)
        self.verticalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_18.setSpacing(0)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.stackedWidget = QtWidgets.QStackedWidget(self.Container)
        self.stackedWidget.setLineWidth(0)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame = QtWidgets.QFrame(self.page)
        self.frame.setStyleSheet("background-color: rgb(28, 31, 34);")
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setStyleSheet("background-color: rgb(175,175,175)")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setStyleSheet("border: none;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_7 = QtWidgets.QFrame(self.frame_3)
        self.frame_7.setStyleSheet("border: none;")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.frame_7)
        self.label_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_2.setStyleSheet("font: 24pt \"Segoe UI\";\n"
"font: 9pt \"Segoe UI\";\n"
"font: 550 48pt \"Segoe UI\";\n"
"border: 2px solid black;\n"
"")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.verticalLayout_2.addWidget(self.frame_7)
        self.verticalLayout_4.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setStyleSheet("border: none;")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame_9 = QtWidgets.QFrame(self.frame_4)
        self.frame_9.setStyleSheet("border: none;")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.frame_15 = QtWidgets.QFrame(self.frame_9)
        self.frame_15.setStyleSheet("border: none;")
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_15)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_8 = QtWidgets.QFrame(self.frame_15)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_3 = QtWidgets.QLabel(self.frame_8)
        self.label_3.setStyleSheet("font: 21pt \"Segoe UI\";\n"
"border: 2px solid black;\n"
"\n"
"color: solid white")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_8.addWidget(self.label_3)
        self.verticalLayout_5.addWidget(self.frame_8)
        self.frame_13 = QtWidgets.QFrame(self.frame_15)
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_13)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_4 = QtWidgets.QLabel(self.frame_13)
        self.label_4.setStyleSheet("font: 19pt \"Segoe UI\";\n"
"border: 2px solid black;\n"
"")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_7.addWidget(self.label_4)
        self.verticalLayout_5.addWidget(self.frame_13)
        self.horizontalLayout_7.addWidget(self.frame_15)
        self.frame_10 = QtWidgets.QFrame(self.frame_9)
        self.frame_10.setStyleSheet("border: none;\n"
"")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.name = QtWidgets.QLineEdit(self.frame_10)
        self.name.setGeometry(QtCore.QRect(0, 20, 251, 51))
        self.name.setStyleSheet("border: 2px solid black;\n"
"\n"
"font: 15pt \"Segoe UI\";\n"
"\n"
"")
        self.name.setObjectName("name")
        self.fathername = QtWidgets.QLineEdit(self.frame_10)
        self.fathername.setGeometry(QtCore.QRect(0, 100, 251, 51))
        self.fathername.setStyleSheet("border: 2px solid black;\n"
"\n"
"font: 15pt \"Segoe UI\";")
        self.fathername.setObjectName("fathername")
        self.horizontalLayout_7.addWidget(self.frame_10)
        self.frame_12 = QtWidgets.QFrame(self.frame_9)
        self.frame_12.setStyleSheet("border: none;")
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_12)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frame_14 = QtWidgets.QFrame(self.frame_12)
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_14)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_5 = QtWidgets.QLabel(self.frame_14)
        self.label_5.setStyleSheet("font: 21pt \"Segoe UI\";\n"
"border: 2px solid black;\n"
"")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_9.addWidget(self.label_5)
        self.verticalLayout_9.addWidget(self.frame_14)
        self.frame_16 = QtWidgets.QFrame(self.frame_12)
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_16)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_6 = QtWidgets.QLabel(self.frame_16)
        self.label_6.setStyleSheet("font: 20pt \"Segoe UI\";\n"
"border: 2px solid black;\n"
"")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_8.addWidget(self.label_6)
        self.verticalLayout_9.addWidget(self.frame_16)
        self.horizontalLayout_7.addWidget(self.frame_12)
        self.frame_11 = QtWidgets.QFrame(self.frame_9)
        self.frame_11.setStyleSheet("border: none;")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.frame_17 = QtWidgets.QFrame(self.frame_11)
        self.frame_17.setGeometry(QtCore.QRect(0, 0, 257, 165))
        self.frame_17.setStyleSheet("border: none;\n"
"")
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.amount = QtWidgets.QLineEdit(self.frame_17)
        self.amount.setGeometry(QtCore.QRect(0, 20, 251, 51))
        self.amount.setStyleSheet("border: 2px solid black;\n"
"\n"
"font: 15pt \"Segoe UI\";")
        self.amount.setObjectName("amount")
        self.location = QtWidgets.QLineEdit(self.frame_17)
        self.location.setGeometry(QtCore.QRect(0, 100, 251, 50))
        self.location.setStyleSheet("border: 2px solid black;\n"
"\n"
"font: 15pt \"Segoe UI\";")
        self.location.setObjectName("location")
        self.horizontalLayout_7.addWidget(self.frame_11)
        self.horizontalLayout_6.addWidget(self.frame_9)
        self.verticalLayout_4.addWidget(self.frame_4)
        self.frame_18 = QtWidgets.QFrame(self.frame_2)
        self.frame_18.setStyleSheet("border: none;")
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_18)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.frame_19 = QtWidgets.QFrame(self.frame_18)
        self.frame_19.setStyleSheet("border: none;")
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_19)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.frame_20 = QtWidgets.QFrame(self.frame_19)
        self.frame_20.setStyleSheet("border: none;")
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_20)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.frame_21 = QtWidgets.QFrame(self.frame_20)
        self.frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_21)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_7 = QtWidgets.QLabel(self.frame_21)
        self.label_7.setStyleSheet("font: 21pt \"Segoe UI\";\n"
"border: 2px solid black;\n"
"")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_12.addWidget(self.label_7)
        self.verticalLayout_10.addWidget(self.frame_21)
        self.frame_22 = QtWidgets.QFrame(self.frame_20)
        self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_22)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_8 = QtWidgets.QLabel(self.frame_22)
        self.label_8.setStyleSheet("font: 20pt \"Segoe UI\";\n"
"border: 2px solid black;\n"
"")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_11.addWidget(self.label_8)
        self.verticalLayout_10.addWidget(self.frame_22)
        self.horizontalLayout_11.addWidget(self.frame_20)
        self.frame_23 = QtWidgets.QFrame(self.frame_19)
        self.frame_23.setStyleSheet("border: none;\n"
"")
        self.frame_23.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.jewellery = QtWidgets.QLineEdit(self.frame_23)
        self.jewellery.setGeometry(QtCore.QRect(0, 20, 251, 51))
        self.jewellery.setStyleSheet("border: 2px solid black;\n"
"\n"
"font: 15pt \"Segoe UI\";")
        self.jewellery.setObjectName("jewellery")
        self.date = QtWidgets.QLineEdit(self.frame_23)
        self.date.setGeometry(QtCore.QRect(0, 100, 251, 51))
        self.date.setStyleSheet("border: 2px solid black;\n"
"\n"
"font: 20pt \"Segoe UI\";")
        self.date.setObjectName("date")
        date=datetime.now().strftime("%Y-%m-%d")
        self.date.setText(date)
        self.horizontalLayout_11.addWidget(self.frame_23)
        self.frame_24 = QtWidgets.QFrame(self.frame_19)
        self.frame_24.setStyleSheet("border: none;")
        self.frame_24.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_24.setObjectName("frame_24")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_24)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.frame_25 = QtWidgets.QFrame(self.frame_24)
        self.frame_25.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_25.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_25.setObjectName("frame_25")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_25)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_9 = QtWidgets.QLabel(self.frame_25)
        self.label_9.setStyleSheet("font: 21pt \"Segoe UI\";\n"
"border: 2px solid black;\n"
"")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_13.addWidget(self.label_9)
        self.frame_26 = QtWidgets.QFrame(self.frame_25)
        self.frame_26.setStyleSheet("border:none;")
        self.frame_26.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_26.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_26.setObjectName("frame_26")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_26)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_10 = QtWidgets.QLabel(self.frame_26)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("border:none;")
        self.label_10.setText("")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_13.addWidget(self.label_10)
        self.verticalLayout_13.addWidget(self.frame_26)
        self.verticalLayout_12.addWidget(self.frame_25)
        self.horizontalLayout_11.addWidget(self.frame_24)
        self.frame_27 = QtWidgets.QFrame(self.frame_19)
        self.frame_27.setStyleSheet("border: none;")
        self.frame_27.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_27.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_27.setObjectName("frame_27")
        self.frame_28 = QtWidgets.QFrame(self.frame_27)
        self.frame_28.setGeometry(QtCore.QRect(0, 0, 257, 165))
        self.frame_28.setStyleSheet("border: none;\n"
"")
        self.frame_28.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_28.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_28.setObjectName("frame_28")
        self.weight = QtWidgets.QLineEdit(self.frame_28)
        self.weight.setGeometry(QtCore.QRect(0, 20, 251, 51))
        self.weight.setStyleSheet("border: 2px solid black;\n"
"\n"
"font: 15pt \"Segoe UI\";")
        self.weight.setObjectName("weight")
        self.deposit = QtWidgets.QLineEdit(self.frame_28)
        self.deposit.setGeometry(QtCore.QRect(0, 100, 251, 50))
        self.deposit.setStyleSheet("border: none;")
        self.deposit.setObjectName("deposit")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_28)
        self.pushButton_2.setGeometry(QtCore.QRect(0, 100, 251, 44))
        self.pushButton_2.setStyleSheet("border: 2px solid black;\n"
"\n"
"background-color: rgb(255, 114, 43);\n"
"font: 20pt \"Segoe UI\";\n"
"\n"
"border-radius: 15px")
        self.pushButton_2.setObjectName("pushButton_2")
        # Create a shortcut for the "Enter" key
        enter_shortcut = QtWidgets.QShortcut(QtGui.QKeySequence(QtCore.Qt.Key_Enter), MainWindow)
        enter_shortcut.activated.connect(self.pushButton_2.click)
        self.pushButton_2.clicked.connect(self.add_record)
        self.horizontalLayout_11.addWidget(self.frame_27)
        self.horizontalLayout_10.addWidget(self.frame_19)
        self.verticalLayout_4.addWidget(self.frame_18)
        self.frame_6 = QtWidgets.QFrame(self.frame_2)
        self.frame_6.setStyleSheet("border:none;")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.frame_5 = QtWidgets.QFrame(self.frame_6)
        self.frame_5.setStyleSheet("border:none;")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.frame_31 = QtWidgets.QFrame(self.frame_5)
        self.frame_31.setStyleSheet("border:none;")
        self.frame_31.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_31.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_31.setObjectName("frame_31")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame_31)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_11 = QtWidgets.QLabel(self.frame_31)
        self.label_11.setStyleSheet("font: 26pt \"Segoe UI\";")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_15.addWidget(self.label_11)
        self.verticalLayout_14.addWidget(self.frame_31)
        self.frame_32 = QtWidgets.QFrame(self.frame_5)
        self.frame_32.setStyleSheet("border:none;")
        self.frame_32.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_32.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_32.setObjectName("frame_32")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.frame_32)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_12 = QtWidgets.QLabel(self.frame_32)
        self.label_12.setStyleSheet("font: 25pt \"Segoe UI\";")
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_16.addWidget(self.label_12)
        self.verticalLayout_14.addWidget(self.frame_32)
        self.horizontalLayout_14.addWidget(self.frame_5)
        self.frame_29 = QtWidgets.QFrame(self.frame_6)
        self.frame_29.setStyleSheet("image: url(:/resources/resources/images/download.png);")
        self.frame_29.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_29.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_29.setObjectName("frame_29")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.frame_29)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.horizontalLayout_14.addWidget(self.frame_29)
        self.frame_30 = QtWidgets.QFrame(self.frame_6)
        self.frame_30.setStyleSheet("border:none;")
        self.frame_30.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_30.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_30.setObjectName("frame_30")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.frame_30)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.pushButton = QtWidgets.QPushButton(self.frame_30)
        self.pushButton.setStyleSheet("border: 2px solid black;\n"
"\n"
"font: 20pt \"Segoe UI\";\n"
"background-color: rgb(3, 53, 127);\n"
"border-radius: 15px")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_17.addWidget(self.pushButton)
        self.horizontalLayout_14.addWidget(self.frame_30)
        self.verticalLayout_4.addWidget(self.frame_6)
        self.horizontalLayout_5.addWidget(self.frame_2)
        self.verticalLayout_6.addWidget(self.frame)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.stackedWidget.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.stackedWidget.addWidget(self.page_5)
        self.verticalLayout_18.addWidget(self.stackedWidget)
        self.horizontalLayout.addWidget(self.Container)
        self.verticalLayout.addWidget(self.Body)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setStyleSheet("QStatusBar {\n"
"    background-color: rgb(10, 11, 12);\n"
"}")
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Add New Record"))
        self.label.setText(_translate("MainWindow", "Loan Management System"))
        self.label_2.setText(_translate("MainWindow", "Add New Record"))
        self.label_3.setText(_translate("MainWindow", "Name"))
        self.label_4.setText(_translate("MainWindow", "Father\'s Name"))
        self.label_5.setText(_translate("MainWindow", "Amount"))
        self.label_6.setText(_translate("MainWindow", "Location"))
        self.label_7.setText(_translate("MainWindow", "Jewellery"))
        self.label_8.setText(_translate("MainWindow", "Date"))
        self.label_9.setText(_translate("MainWindow", "Weight"))
        self.pushButton_2.setText(_translate("MainWindow", "Add Record"))
        self.label_11.setText(_translate("MainWindow", "Biometric"))
        self.label_12.setText(_translate("MainWindow", "Identification"))
        self.pushButton.setText(_translate("MainWindow", "Add Fingerprint"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
